scheduler_type: const
optimizer:
  lr: 0.0001
  batch_size: 8
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  anneal_steps: [100000]
  anneal_rate: 0.3
step:
  total_step: 50000
  log_step: 100
  synth_step: 2500
  val_step: 2500
  save_step: 5000
